### ISSUE TITLE
CLI 5 not compatible with Ruby 2.5

### ISSUE THREAD

**Issue by dividedmind** [cyberark/conjur-cli#203]
I've tried running the CLI and encountered a number of issues, such as:
- missing `openssl` require,
- rest-client < 2.0 don't support Ruby 2.5.

To reproduce:
```
$ docker run --entrypoint bash -it ruby:2.5.0
# gem install conjur-cli --version '~> 5'
# conjur init -h www.google.com
```

**Comment by uCatu** [comment]
Adding stacktracke:
```
Traceback (most recent call last):
	11: from /usr/local/bundle/bin/conjur:23:in `<main>'
	10: from /usr/local/bundle/bin/conjur:23:in `load'
	 9: from /usr/local/bundle/gems/conjur-cli-5.6.6/bin/conjur:24:in `<top (required)>'
	 8: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/cli.rb:35:in `<top (required)>'
	 5: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/cli.rb:49:in `<module:Conjur>'
	 4: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/cli.rb:111:in `<class:CLI>'
	 3: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/cli.rb:92:in `init!'
	 2: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/cli.rb:60:in `apply_config'
	 1: from /usr/local/bundle/gems/conjur-cli-5.6.6/lib/conjur/config.rb:105:in `apply'
/usr/local/bundle/gems/conjur-api-4.31.0/lib/conjur/configuration.rb:423:in `apply_cert_config!': uninitialized constant Conjur::Configuration::OpenSSL (NameError)
Did you mean?  OpenStruct
```

*This bug is reoccuring also on EE workspace.*
```
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
$ openssl version
OpenSSL 1.1.1c FIPS  28 May 2019
```
