### ISSUE TITLE
CLI does not run anymore - xdg `'require_relative': cannot load such file` error

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-cli#243]
Error when gem is installed:
```
Traceback (most recent call last):
        10: from /usr/local/bundle/bin/conjur:23:in `<main>'
         9: from /usr/local/bundle/bin/conjur:23:in `load'
         8: from /usr/local/bundle/gems/conjur-cli-6.0.0/bin/conjur:24:in `<top (required)>'
         7: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /usr/local/bundle/gems/conjur-cli-6.0.0/lib/conjur/cli.rb:25:in `<top (required)>'
         4: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /usr/local/bundle/gems/xdg-2.2.4/lib/xdg.rb:26:in `<top (required)>'
         1: from /usr/local/bundle/gems/xdg-2.2.4/lib/xdg.rb:28:in `<module:XDG>'
/usr/local/bundle/gems/xdg-2.2.4/lib/xdg.rb:28:in `require_relative': cannot load such file -- /usr/local/bundle/gems/xdg-2.2.4/lib/xdg/index (LoadError)
```

Looks to be caused by xdg 2.2.4 gem. Pin to 2.2.3 makes the CLI work again.

**Comment by sgnn7** [comment]
Fix released with [v6.2.1](https://github.com/cyberark/conjur-cli/releases/tag/v6.2.1)
